Problem :

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Solution :

class Solution {
    public char findTheDifference(String s, String t) 
    {
        int cnts[]=new int[26];
        int cntt[]=new int[26];

        for(int i=0;i<s.length();i++)
        {
            char c=s.charAt(i);
            cnts[c-'a']++;
        }
        for(int i=0;i<t.length();i++)
        {
            char c=t.charAt(i);
            cntt[c-'a']++;
        }
        for(int i=0;i<26;i++)
        {
            if(cnts[i]!=cntt[i])
            {
                return (char)(i+'a');
            }
        }
        return ' ';
    }
}
